import { useDispatch } from "react-redux";
import { bindActionCreators } from "redux";
import { authActionCreators,
   getMyProfile,
   getMySupporter,
   getMyGraph ,
   getSpin,
   getSupporterProfile,
   getSupporterSupporterList,
   getSupporterGraph,
   getMyInterest,
   deleteMyInterest,
   addNew_Interest,
   getMyTimeline,
   getSupporterTimeline,
   uploadProfilePicture,
   signUp,
   updateMyProfile,
   getResume,
   deleteResume,
   resumeDetail,
   resume_CategoryList,
   getMessageList,
   getMessageDetail,
   sendMessage,
   searchSupporter,
   getCategories,
   addCategory,
   deleteCategory,
   updateCategory,
   setsupport,
   deleteTimelineItem,
   UpdateInterest,
   getNotifications,
   clear_Notificatins,
   setFollowUnfollow} from "../store";

export const useActions = () => {
  const dispatch = useDispatch();
  return bindActionCreators(
    Object.assign(
      {},
      authActionCreators,
      getMyProfile,
      getMySupporter,
      getMyGraph,
      getSpin,
      getSupporterProfile,
      getSupporterSupporterList,
      getSupporterGraph,
      getMyInterest,
      deleteMyInterest,
      addNew_Interest,
      getMyTimeline,
      getSupporterTimeline,
      uploadProfilePicture,
      signUp,
      updateMyProfile,
      getResume,
      deleteResume,
      resumeDetail,
      resume_CategoryList,
      getMessageList,
      getMessageDetail,
      sendMessage,
      searchSupporter,
      getCategories,
      addCategory,
      deleteCategory,
      updateCategory,
      setsupport,
      deleteTimelineItem,
      UpdateInterest,
      getNotifications,
      clear_Notificatins,
      setFollowUnfollow,
    ),
    dispatch,
  );
};
