import navigaionIcon from '../assets/navigateIcon/navigateIcon.png';
import imageLayout from '../assets/imageLayout/imageLayout.png';
import demoImage from '../assets/demoImage/demoImage.png';
import dp from '../assets/dp/dp.png';
import loc from '../assets/loc/loc.png';
import back from '../assets/back/back.png';
import follow from '../assets/follow/follow.png';
import dummy from '../assets/dummy/dummy.png';
import edit from '../assets/edit/edit.png';
import deletei from '../assets/delete/delete.png';
import add from '../assets/add/add.png';
import dots from '../assets/dots/dots.png';
import support from '../assets/support/support.png';
import comment from '../assets/comment/comment.png';
import share from '../assets/share/share.png';
import camera from '../assets/camera/camera.png';
import pdf from '../assets/pdf/pdf.png';
import calender from '../assets/calender/calendar.png';
import pdfwhite from '../assets/pdfwhite/pdfwhite.png';
import word from '../assets/word/word.png';
import doc from '../assets/doc/doc.png';
import search from '../assets/search/search.png';
import send from '../assets/send/send.png';
import addCategory from '../assets/addCategory/addCategory.png'
import editBlack from '../assets/editBlack/editBlack.png'
import deleteBlack from '../assets/deleteBlack/deleteBlack.png'
import addWhite from '../assets/addWhite/addWhite.png';
import close from '../assets/close/close.png';
import addresume from '../assets/addresume/addresume.png'
import slidebc from '../assets/slidebc/slidebc.png'
import dash from '../assets/dash/dash.png'
import searchwhite from '../assets/searchwhite/searchwhite.png'
import closewhite from '../assets/closewhite/closewhite.png'
import bookmark from '../assets/bookmark/bookmark.png'

export {navigaionIcon, imageLayout, demoImage,dp,loc,back,follow,dummy,edit,deletei,add,dots,support,comment,share,camera,pdf,calender,pdfwhite,word,doc,search,send,addCategory,editBlack,deleteBlack,addWhite,close,addresume,slidebc,dash,searchwhite,closewhite,bookmark};
