export default {
  LOGIN: 'Login',
  SIGNUP:'SignUp',
  SIGNUP_STEP_2:'Sign Up Step 2',
  TAB_BAR_HOME: 'Home',
  TAB_BAR_SPIN: 'Spin',
  TAB_BAR_MESSAGES: 'Message',
  TAB_BAR_DASH:'College List',
  TAB_BAR_RESUME: 'Resume',
  MY_WHEEL:'My Wheel',
  SUPPORTERS :'SUPPORTERS',
  MYPROFILE:'My Profile',
  SUPPORTER_PROFILE:'Supporter Profile',
  INTERESTS:'My Interest',
  ADDNEWINTEREST:'Add Interest',
  UPDATE_PROFILE : 'Update Profile',
  MESSAGE_DETAIL:'CHAT',
  ADD_NEW_CATEGORY:'Add Category',
  FAQ:'Frequently Asked Question',
  PRIVACY_POLICY:'Privacy Policy',
  ABOUT:'About',
  HELP:'Help',
  NOTIFICATIONS:'Notifications',
  ADD_RESUME:'My Resumes',
  ADD_ACTIVITY:'Activity',
  RESET_PASSWORD:'Reset Password',
  ADD_SUPPORTER:'Add Supporter',
  PAYPAL:'PayPal',
};
